osx_image: xcode8.3
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods -v 1.3.1 # Since Travis is not always on latest version
  - gem install xcpretty
  - pod install --project-directory=Example --repo-update

script:
  - "! git grep ' $'" # Fail on trailing whitespace
  - ./test.sh
  - pod lib lint FirebaseCommunity.podspec --verbose | tail -40
