name: check

on:
  pull_request:
    paths-ignore:
      - 'Firestore/**'

jobs:
  check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup check
      run:  scripts/setup_check.sh

    - name: Check
      run:  scripts/check.sh --test-only
