name: core

on:
  pull_request:
    paths:
    - 'FirebaseCore**'
    - '.github/workflows/core.yml'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  pod_lib_lint:
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: Build and test
      run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=${{ matrix.target }}
