name: CRON

on:
  schedule:
    # Run every day at 1am (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  zip:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up
      run: |
        bundle install
        bundle exec pod --version
    - name: ZipBuildingTest
      run: ./scripts/build_zip.sh
