# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: firestore

on:
  pull_request:
    paths:
    # Firestore sources
    - 'Firestore/**'

    # Podspec
    - 'FirebaseFirestore.podspec'

    # CMake
    - 'CMakeLists.txt'
    - 'cmake/**'

    # Build scripts to which Firestore is sensitive
    #
    # Note that this doesn't include check scripts because changing those will
    # already trigger the check workflow.
    - 'scripts/binary_to_array.py'
    - 'scripts/build.sh'
    - 'scripts/install_prereqs.sh'
    - 'scripts/localize_podfile.swift'
    - 'scripts/pod_lib_lint.rb'
    - 'scripts/run_firestore_emulator.sh'
    - 'scripts/setup_*'
    - 'scripts/sync_project.rb'
    - 'scripts/test_quickstart.sh'
    - 'scripts/xcresult_logs.py'

    # This workflow
    - '.github/workflows/firestore.yml'

  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup check
      run:  scripts/setup_check.sh

    - name: Run check
      run:  scripts/check.sh --test-only


  cmake:
    needs: check

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Prepare ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: firestore-ccache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          firestore-ccache-${{ runner.os }}-

    - name: Setup build
      run:  scripts/install_prereqs.sh Firestore ${{ runner.os }} cmake

    - name: Build and test
      run:  scripts/third_party/travis/retry.sh scripts/build.sh Firestore ${{ runner.os }} cmake


  sanitizers:
    runs-on: macos-latest
    needs: check

    strategy:
      matrix:
        sanitizer: [asan, tsan]

    env:
      SANITIZERS: ${{ matrix.sanitizer }}

    steps:
    - uses: actions/checkout@v2

    - name: Prepare ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: firestore-ccache-${{ runner.os }}-${{ matrix.sanitizer }}-${{ github.sha }}
        restore-keys: |
          firestore-ccache-${{ runner.os }}-${{ matrix.sanitizer }}-

    - name: Setup build
      run:  scripts/install_prereqs.sh Firestore ${{ runner.os }} cmake

    - name: Build and test
      run:  scripts/third_party/travis/retry.sh scripts/build.sh Firestore ${{ runner.os }} cmake


  xcodebuild:
    runs-on: macos-latest
    needs: check

    strategy:
      matrix:
        target: [iOS, tvOS, macOS]

    steps:
    - uses: actions/checkout@v2

    - name: Setup build
      run:  scripts/install_prereqs.sh Firestore ${{ matrix.target }} xcodebuild

    - name: Build and test
      run:  scripts/third_party/travis/retry.sh scripts/build.sh Firestore ${{ matrix.target }} xcodebuild


  pod-lib-lint:
    runs-on: macos-latest
    needs: check

    steps:
    - uses: actions/checkout@v2

    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh

    - name: Pod lib lint
      run: |
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseFirestore.podspec \
            --platforms=ios \
            --allow-warnings
