name: spm

on:
  pull_request:
    paths:
    - '.github/workflows/spm.yml'
    - 'Package.swift'
    - 'Firebase**'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  swift-build-run:
    # Don't run on private repo unless it is a PR.
    if: github.repository != 'FirebasePrivate/firebase-ios-sdk' || github.event_name == 'pull_request'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12_beta.app/Contents/Developer
    - name: Build
      run: swift build
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Core ObjC Unit Tests macOS
      run:  scripts/third_party/travis/retry.sh xcodebuild -scheme Firebase-Package test | xcpretty
    - name: Core ObjC Unit Tests iOS
      run: scripts/third_party/travis/retry.sh xcodebuild -scheme Firebase-Package test -sdk
           iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
    - name: Core ObjC Unit Tests tvOS
      run: scripts/third_party/travis/retry.sh xcodebuild -scheme Firebase-Package test -sdk
           appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty
