name: symbolcollision

# Tests the Pods listed in SymbolCollisionTest/Podfile for symbol collisions.

on:
  pull_request:
    paths:
    - '.github/workflows/symbolcollision.yml'
    - 'SymbolCollisionTest/**'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  installation-test:
    # Don't run on private repo unless it is a PR.
    if: github.repository != 'FirebasePrivate/firebase-ios-sdk' || github.event_name == 'pull_request'
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Prereqs
      run: scripts/install_prereqs.sh SymbolCollision iOS
    - name: Build
      run: scripts/build.sh SymbolCollision iOS
